"""The WorldCast generator ``G_theta`` and its conditioning, the state model with its depth head,
and the Wan2.2 VAE and text encoder.

Each component is usable on its own; the names below are imported on first use (PEP 562).
"""

from worldcast.utils.lazy import lazy_exports

__getattr__, __dir__, __all__ = lazy_exports(
    __name__,
    {
        "build": (
            "CHECKPOINT_ROOT",
            "EMA_KEY",
            "ONLINE_KEY",
            "build_inference_generator",
            "generator_config_from_snapshot",
            "load_generator",
            "optional_modules",
            "read_generator",
        ),
        "controls": ("BUTTONS", "CONTROL_KEYS", "VIEW_DELTAS", "ControlConfig", "ControlEmbedding"),
        "depth_head": (
            "DepthFn",
            "DepthHead",
            "DepthPredictor",
            "DepthReadout",
            "load_depth_predictor",
        ),
        "observer_signals": ("ObserverSignalConfig", "ObserverSignalEmbedding", "ObserverSignals"),
        "ray_embedding": ("RAY_CONDITION_KEYS", "RayConditions", "RayEmbedding", "plucker_rays"),
        "state_injector": (
            "FIELD_CHANNEL_NAMES",
            "FIELD_CONTROLS",
            "WEAPON_CHANNELS",
            "StateInjector",
            "StateInjectorConfig",
            "log_compressed_depth",
        ),
        "state_model": (
            "CELL_SIZE",
            "DISPLACEMENT_UNIT_U",
            "MAPS",
            "STATE_MODEL_WINDOW_LATENT_FRAMES",
            "STATE_MODEL_WINDOW_STRIDE",
            "CellTable",
            "StateModel",
            "StateModelOutput",
            "load_cell_table",
            "load_state_model",
            "map_index",
        ),
        "visibility_probe": (
            "VisibilityProbe",
            "VisibilityProbeConfig",
            "VisibilityProbeInputs",
            "visibility_bce",
        ),
        "wan22.attention": (
            "ATTENTION_KERNELS",
            "PAPER_ATTENTION",
            "AttentionFn",
            "MaskLayout",
            "TrainingMask",
            "attention_kernel",
            "causal_blocks",
            "fa3_attention",
            "fa3_available",
            "flash_attention",
            "flash_attention_backend",
            "masked_attention",
            "sdpa_attention",
            "training_mask",
        ),
        "wan22.dit": ("DIT_BLOCK_PARTS", "DiTBlockParts", "KVCache"),
        "wan22.model": (
            "WORLDCAST_MODULES",
            "CallPlan",
            "CallPrologue",
            "CausalGeneratorAdapter",
            "FieldBuilder",
            "GeneratorConditions",
            "GeneratorConfig",
            "PlayerStateFieldFn",
            "WorldCastGenerator",
            "call_inputs",
            "conditions_with_field",
            "worldcast_module",
        ),
        "wan22.text_encoder": (
            "FIXED_PROMPT",
            "T5_CHECKPOINT_NAME",
            "TOKENIZER_SUBDIR",
            "TextEncoder",
            "Tokenizer",
            "UMT5Config",
            "UMT5Encoder",
            "UMT5Tokenizer",
            "load_prompt_embedding",
            "load_text_encoder",
            "save_prompt_embedding",
        ),
        "wan22.training": ("TrainingForward", "forward_train"),
        "wan22.vae": (
            "VAE_CHECKPOINT_NAME",
            "VAEConfig",
            "Wan22StreamingDecoder",
            "Wan22VAE",
            "latent_scale",
            "load_wan22_vae",
        ),
    },
)
